theme: minima
title: My first blog on Github with Jekyll
author: Gastón Albán
email: ggllaacc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aca la descripción sin meta, asíque google no estará en el top de búsqueda de
  Google.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/GS7N # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
  pequeño mini blog
